// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `install_result_dto`

/// Creates the process-wide Core. Every subsequent call returns an error,
/// including calls with identical config. Restart the process to change roots.
Future<BridgeInfo> initCore({required BridgeConfig config}) =>
    RustLib.instance.api.crateApiCoreInitCore(config: config);

/// One active subscriber; registering again replaces/closes the previous stream.
/// Wait for Ready before triggering an action whose events must be observed.
Stream<BridgeEvent> coreEvents() =>
    RustLib.instance.api.crateApiCoreCoreEvents();

Future<LocalSchemaDto> checkLocalSchema() =>
    RustLib.instance.api.crateApiCoreCheckLocalSchema();

Future<OnboardingDto> onboarding() =>
    RustLib.instance.api.crateApiCoreOnboarding();

Future<void> completeOnboarding() =>
    RustLib.instance.api.crateApiCoreCompleteOnboarding();

Future<SchemeReleaseDto> fetchSchemeRelease({required String scheme}) =>
    RustLib.instance.api.crateApiCoreFetchSchemeRelease(scheme: scheme);

/// Fetches the latest release for the same scheme key accepted by Core,
/// downloads it, then installs into the host root. Does not deploy the IME.
Future<InstallResultDto> installLatestScheme({required String scheme}) =>
    RustLib.instance.api.crateApiCoreInstallLatestScheme(scheme: scheme);

Future<ReleaseInfoDto> fetchLatestRelease() =>
    RustLib.instance.api.crateApiCoreFetchLatestRelease();

Future<AppUpdateDto> checkAppUpdate() =>
    RustLib.instance.api.crateApiCoreCheckAppUpdate();

/// Reads a filesystem directory. Android SAF tree URIs use the readLocalSchemas
/// platform channel instead. Both Core-supported custom-config filenames count.
Future<LocalSchemasDto> readLocalSchemas({required String dir}) =>
    RustLib.instance.api.crateApiCoreReadLocalSchemas(dir: dir);

/// Returns Core's directory-first, name-sorted entries. SAF uses listFiles.
Future<List<FileItemDto>> listDir({required String dir}) =>
    RustLib.instance.api.crateApiCoreListDir(dir: dir);

/// Downloads and smart-installs into the selected filesystem directory without
/// deploying. Android SAF uses download_scheme_archive and smartExtractZip.
Future<InstallResultDto> installSchemeToDir({
  required String url,
  required String dir,
}) => RustLib.instance.api.crateApiCoreInstallSchemeToDir(url: url, dir: dir);

/// Android SAF sequence: confirm storage permission/migration, pickDirectory,
/// then listFiles/readLocalSchemas through the platform channel. Download here,
/// call smartExtractZip(zipPath, treeUri) with its progress handler, and pass
/// jsonEncode(result) to finish_android_install for the DTO and done event.
/// Always call remove_downloaded_archive in Dart's finally block. Do not deploy
/// or copy into the private/live root. Download progress uses core_events.
/// Dart must serialize this entire sequence with all other installations:
/// Core's fixed cache filename is protected only during each Rust call.
Future<String> downloadSchemeArchive({required String url}) =>
    RustLib.instance.api.crateApiCoreDownloadSchemeArchive(url: url);

/// Cleans up the SAF download after smartExtractZip succeeds or fails. Missing
/// files are already clean (Kotlin removes the zip on success). Resolves parent
/// directories and rejects symlink files before deleting inside the cache.
Future<void> removeDownloadedArchive({required String path}) =>
    RustLib.instance.api.crateApiCoreRemoveDownloadedArchive(path: path);

/// Installs a selected GitHub/Gitee or scheme release URL without deploying.
Future<InstallResultDto> installSchemeFromUrl({required String url}) =>
    RustLib.instance.api.crateApiCoreInstallSchemeFromUrl(url: url);

/// Call only after the Android channel confirms storage permission. Dart must
/// serialize prepare -> smartExtractZipToPrivate -> finish as one installation.
Future<String> prepareAndroidInstall({required String url}) =>
    RustLib.instance.api.crateApiCorePrepareAndroidInstall(url: url);

/// Pass jsonEncode of the Android channel's smart-extract result unchanged.
Future<InstallResultDto> finishAndroidInstall({required String resultJson}) =>
    RustLib.instance.api.crateApiCoreFinishAndroidInstall(
      resultJson: resultJson,
    );

/// Android deployment belongs to the deployImeData platform channel.
Future<DeployResultDto> deployDefault() =>
    RustLib.instance.api.crateApiCoreDeployDefault();

Future<AndroidImeInputSettingsDto> getAndroidImeInputSettings() =>
    RustLib.instance.api.crateApiCoreGetAndroidImeInputSettings();

/// Saves all 23 writable fields; returned path/message fields are read-only.
Future<AndroidImeInputSettingsDto> setAndroidImeInputSettings({
  required AndroidImeInputSettingsDto settings,
}) => RustLib.instance.api.crateApiCoreSetAndroidImeInputSettings(
  settings: settings,
);

Future<ImeUiSettingsDto> getImeUiSettings() =>
    RustLib.instance.api.crateApiCoreGetImeUiSettings();

Future<ImeUiSettingsDto> setImeUiSettings({
  required UiColorSchemeDto colorScheme,
  required PanelOrientationDto orientation,
  required String accentColor,
  required double fontSize,
}) => RustLib.instance.api.crateApiCoreSetImeUiSettings(
  colorScheme: colorScheme,
  orientation: orientation,
  accentColor: accentColor,
  fontSize: fontSize,
);

Future<ImeUiSettingsDto> setImeEmbeddedComposition({required bool embedded}) =>
    RustLib.instance.api.crateApiCoreSetImeEmbeddedComposition(
      embedded: embedded,
    );

Future<EnglishModeDto> getDesktopEnglishMode() =>
    RustLib.instance.api.crateApiCoreGetDesktopEnglishMode();

Future<EnglishModeDto> setDesktopEnglishMode({required EnglishModeDto mode}) =>
    RustLib.instance.api.crateApiCoreSetDesktopEnglishMode(mode: mode);

Future<AddonSchemaStatusDto> addonSchemaStatus({required String id}) =>
    RustLib.instance.api.crateApiCoreAddonSchemaStatus(id: id);

/// Android: await copyAddonSchemaAssets(id) through the platform channel first;
/// this call's host treats copy_addon_assets as already complete. android_deploy
/// must await deployImeData and return "" on success or error text on failure,
/// catching Dart exceptions. Do not re-enter bridge install/deploy calls from
/// the callback: the install lock is held. macOS ignores the callback and uses
/// the existing bridge deploy. InstallProgress continues through core_events.
Future<AddonSchemaStatusDto> addonSchemaInstall({
  required String id,
  required FutureOr<String> Function() androidDeploy,
}) => RustLib.instance.api.crateApiCoreAddonSchemaInstall(
  id: id,
  androidDeploy: androidDeploy,
);

/// Uses the same per-call deploy contract as addon_schema_install; no asset copy
/// is needed. Core owns schema removal, English-mode reset and progress events.
Future<AddonSchemaStatusDto> addonSchemaUninstall({
  required String id,
  required FutureOr<String> Function() androidDeploy,
}) => RustLib.instance.api.crateApiCoreAddonSchemaUninstall(
  id: id,
  androidDeploy: androidDeploy,
);

Future<WanxiangStatusDto> wanxiangStatus() =>
    RustLib.instance.api.crateApiCoreWanxiangStatus();

/// Uses addon_schema_install's deploy contract. Core keeps its receipt/rollback
/// flow unchanged and may call android_deploy again after restoring files.
/// The install lock covers the whole operation, including rollback/deployment.
Future<WanxiangStatusDto> manageWanxiang({
  required bool installed,
  required FutureOr<String> Function() androidDeploy,
}) => RustLib.instance.api.crateApiCoreManageWanxiang(
  installed: installed,
  androidDeploy: androidDeploy,
);

Future<MacosImeStatusDto> macosImeStatus() =>
    RustLib.instance.api.crateApiCoreMacosImeStatus();

Future<ComponentVersionsDto> getComponentVersions() =>
    RustLib.instance.api.crateApiCoreGetComponentVersions();

Future<RuntimeLogSettingsDto> getRuntimeLogSettings() =>
    RustLib.instance.api.crateApiCoreGetRuntimeLogSettings();

Future<void> setRuntimeLogSettings({
  required bool enabled,
  required RuntimeLogLevelDto level,
}) => RustLib.instance.api.crateApiCoreSetRuntimeLogSettings(
  enabled: enabled,
  level: level,
);

Future<DebugLogFileDto> readRuntimeLog({int? maxLines}) =>
    RustLib.instance.api.crateApiCoreReadRuntimeLog(maxLines: maxLines);

Future<DebugLogsDto> readDebugLogs() =>
    RustLib.instance.api.crateApiCoreReadDebugLogs();

Future<void> clearRuntimeLog() =>
    RustLib.instance.api.crateApiCoreClearRuntimeLog();
