// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

/// Creates the process-wide Core. Every subsequent call returns an error,
/// including calls with identical config. Restart the process to change roots.
Future<BridgeInfo> initCore({required BridgeConfig config}) =>
    RustLib.instance.api.crateApiCoreInitCore(config: config);

/// One active subscriber; registering again replaces/closes the previous stream.
/// Wait for Ready before triggering an action whose events must be observed.
Stream<BridgeEvent> coreEvents() =>
    RustLib.instance.api.crateApiCoreCoreEvents();

Future<LocalSchemaDto> checkLocalSchema() =>
    RustLib.instance.api.crateApiCoreCheckLocalSchema();

Future<OnboardingDto> onboarding() =>
    RustLib.instance.api.crateApiCoreOnboarding();

Future<void> completeOnboarding() =>
    RustLib.instance.api.crateApiCoreCompleteOnboarding();

Future<SchemeReleaseDto> fetchSchemeRelease({required String scheme}) =>
    RustLib.instance.api.crateApiCoreFetchSchemeRelease(scheme: scheme);

/// Fetches the latest release for the same scheme key accepted by Core,
/// downloads it, then installs into the host root. Does not deploy the IME.
Future<InstallResultDto> installLatestScheme({required String scheme}) =>
    RustLib.instance.api.crateApiCoreInstallLatestScheme(scheme: scheme);
