// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

class AddonSchemaStatusDto {
  final bool installed;
  final bool deployed;
  final String version;
  final bool englishAvailable;

  const AddonSchemaStatusDto({
    required this.installed,
    required this.deployed,
    required this.version,
    required this.englishAvailable,
  });

  @override
  int get hashCode =>
      installed.hashCode ^
      deployed.hashCode ^
      version.hashCode ^
      englishAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddonSchemaStatusDto &&
          runtimeType == other.runtimeType &&
          installed == other.installed &&
          deployed == other.deployed &&
          version == other.version &&
          englishAvailable == other.englishAvailable;
}

class AndroidImeInputSettingsDto {
  final bool hapticsEnabled;
  final int hapticIntensity;
  final String enterKeyBehavior;
  final bool keyPreviewEnabled;
  final int longPressDelayMs;
  final int keyboardHeightScale;
  final String deleteSpeed;
  final String englishMode;
  final String backspaceGestureMode;
  final int keyboardHeightDp;
  final int candidateBarHeightDp;
  final double swipeThresholdDp;
  final bool keySoundEnabled;
  final int keySoundVolume;
  final bool keyHintVisible;
  final bool flickKeysEnabled;
  final bool numberRowEnabled;
  final double candidateFontScale;
  final bool doubleSpacePeriodEnabled;
  final bool floatingPortraitEnabled;
  final int floatingPortraitScale;
  final bool floatingLandscapeEnabled;
  final int floatingLandscapeScale;
  final String? configPath;
  final String? reloadStampPath;
  final String message;

  const AndroidImeInputSettingsDto({
    required this.hapticsEnabled,
    required this.hapticIntensity,
    required this.enterKeyBehavior,
    required this.keyPreviewEnabled,
    required this.longPressDelayMs,
    required this.keyboardHeightScale,
    required this.deleteSpeed,
    required this.englishMode,
    required this.backspaceGestureMode,
    required this.keyboardHeightDp,
    required this.candidateBarHeightDp,
    required this.swipeThresholdDp,
    required this.keySoundEnabled,
    required this.keySoundVolume,
    required this.keyHintVisible,
    required this.flickKeysEnabled,
    required this.numberRowEnabled,
    required this.candidateFontScale,
    required this.doubleSpacePeriodEnabled,
    required this.floatingPortraitEnabled,
    required this.floatingPortraitScale,
    required this.floatingLandscapeEnabled,
    required this.floatingLandscapeScale,
    this.configPath,
    this.reloadStampPath,
    required this.message,
  });

  @override
  int get hashCode =>
      hapticsEnabled.hashCode ^
      hapticIntensity.hashCode ^
      enterKeyBehavior.hashCode ^
      keyPreviewEnabled.hashCode ^
      longPressDelayMs.hashCode ^
      keyboardHeightScale.hashCode ^
      deleteSpeed.hashCode ^
      englishMode.hashCode ^
      backspaceGestureMode.hashCode ^
      keyboardHeightDp.hashCode ^
      candidateBarHeightDp.hashCode ^
      swipeThresholdDp.hashCode ^
      keySoundEnabled.hashCode ^
      keySoundVolume.hashCode ^
      keyHintVisible.hashCode ^
      flickKeysEnabled.hashCode ^
      numberRowEnabled.hashCode ^
      candidateFontScale.hashCode ^
      doubleSpacePeriodEnabled.hashCode ^
      floatingPortraitEnabled.hashCode ^
      floatingPortraitScale.hashCode ^
      floatingLandscapeEnabled.hashCode ^
      floatingLandscapeScale.hashCode ^
      configPath.hashCode ^
      reloadStampPath.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AndroidImeInputSettingsDto &&
          runtimeType == other.runtimeType &&
          hapticsEnabled == other.hapticsEnabled &&
          hapticIntensity == other.hapticIntensity &&
          enterKeyBehavior == other.enterKeyBehavior &&
          keyPreviewEnabled == other.keyPreviewEnabled &&
          longPressDelayMs == other.longPressDelayMs &&
          keyboardHeightScale == other.keyboardHeightScale &&
          deleteSpeed == other.deleteSpeed &&
          englishMode == other.englishMode &&
          backspaceGestureMode == other.backspaceGestureMode &&
          keyboardHeightDp == other.keyboardHeightDp &&
          candidateBarHeightDp == other.candidateBarHeightDp &&
          swipeThresholdDp == other.swipeThresholdDp &&
          keySoundEnabled == other.keySoundEnabled &&
          keySoundVolume == other.keySoundVolume &&
          keyHintVisible == other.keyHintVisible &&
          flickKeysEnabled == other.flickKeysEnabled &&
          numberRowEnabled == other.numberRowEnabled &&
          candidateFontScale == other.candidateFontScale &&
          doubleSpacePeriodEnabled == other.doubleSpacePeriodEnabled &&
          floatingPortraitEnabled == other.floatingPortraitEnabled &&
          floatingPortraitScale == other.floatingPortraitScale &&
          floatingLandscapeEnabled == other.floatingLandscapeEnabled &&
          floatingLandscapeScale == other.floatingLandscapeScale &&
          configPath == other.configPath &&
          reloadStampPath == other.reloadStampPath &&
          message == other.message;
}

class AppUpdateDto {
  final bool hasUpdate;
  final String latestVersion;
  final String currentVersion;
  final String releaseUrl;

  const AppUpdateDto({
    required this.hasUpdate,
    required this.latestVersion,
    required this.currentVersion,
    required this.releaseUrl,
  });

  @override
  int get hashCode =>
      hasUpdate.hashCode ^
      latestVersion.hashCode ^
      currentVersion.hashCode ^
      releaseUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppUpdateDto &&
          runtimeType == other.runtimeType &&
          hasUpdate == other.hasUpdate &&
          latestVersion == other.latestVersion &&
          currentVersion == other.currentVersion &&
          releaseUrl == other.releaseUrl;
}

class BridgeConfig {
  final String dataDir;
  final String cacheDir;
  final String resourceDir;
  final String appVersion;
  final BridgePlatform platform;

  /// An absolute path. When set, all bridge hosts use this root exclusively.
  final String? userRootOverride;

  const BridgeConfig({
    required this.dataDir,
    required this.cacheDir,
    required this.resourceDir,
    required this.appVersion,
    required this.platform,
    this.userRootOverride,
  });

  @override
  int get hashCode =>
      dataDir.hashCode ^
      cacheDir.hashCode ^
      resourceDir.hashCode ^
      appVersion.hashCode ^
      platform.hashCode ^
      userRootOverride.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeConfig &&
          runtimeType == other.runtimeType &&
          dataDir == other.dataDir &&
          cacheDir == other.cacheDir &&
          resourceDir == other.resourceDir &&
          appVersion == other.appVersion &&
          platform == other.platform &&
          userRootOverride == other.userRootOverride;
}

/// Exactly one payload is present for progress/status events; action/ready have none.
/// Plain structs avoid requiring any Dart code-generation packages.
class BridgeEvent {
  final BridgeEventKind kind;
  final InstallProgressDto? installProgress;
  final String? deployProgress;
  final WindowsImeStatusDto? windowsImeStatus;

  const BridgeEvent({
    required this.kind,
    this.installProgress,
    this.deployProgress,
    this.windowsImeStatus,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      installProgress.hashCode ^
      deployProgress.hashCode ^
      windowsImeStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          installProgress == other.installProgress &&
          deployProgress == other.deployProgress &&
          windowsImeStatus == other.windowsImeStatus;
}

enum BridgeEventKind {
  /// Subscription handshake; subsequent events come from Core's EventSink.
  ready,
  installProgress,
  deployProgress,
  windowsImeStatus,
  windowsImeAction,
}

class BridgeInfo {
  final BridgePlatform platform;
  final String appVersion;
  final String userRoot;

  const BridgeInfo({
    required this.platform,
    required this.appVersion,
    required this.userRoot,
  });

  @override
  int get hashCode =>
      platform.hashCode ^ appVersion.hashCode ^ userRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeInfo &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          appVersion == other.appVersion &&
          userRoot == other.userRoot;
}

enum BridgePlatform { windows, macOs, linux, android, ios }

class ComponentVersionsDto {
  final String appVersion;
  final String? librimeVersion;
  final String? openccVersion;
  final String? dataDir;

  const ComponentVersionsDto({
    required this.appVersion,
    this.librimeVersion,
    this.openccVersion,
    this.dataDir,
  });

  @override
  int get hashCode =>
      appVersion.hashCode ^
      librimeVersion.hashCode ^
      openccVersion.hashCode ^
      dataDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComponentVersionsDto &&
          runtimeType == other.runtimeType &&
          appVersion == other.appVersion &&
          librimeVersion == other.librimeVersion &&
          openccVersion == other.openccVersion &&
          dataDir == other.dataDir;
}

class DebugLogFileDto {
  final List<String> lines;
  final bool truncated;

  const DebugLogFileDto({required this.lines, required this.truncated});

  @override
  int get hashCode => lines.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DebugLogFileDto &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          truncated == other.truncated;
}

class DebugLogsDto {
  final DebugLogFileDto ime;
  final DebugLogFileDto app;
  final DebugLogFileDto? macosIme;

  const DebugLogsDto({required this.ime, required this.app, this.macosIme});

  @override
  int get hashCode => ime.hashCode ^ app.hashCode ^ macosIme.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DebugLogsDto &&
          runtimeType == other.runtimeType &&
          ime == other.ime &&
          app == other.app &&
          macosIme == other.macosIme;
}

class DeployResultDto {
  final bool success;
  final String message;

  const DeployResultDto({required this.success, required this.message});

  @override
  int get hashCode => success.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeployResultDto &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message;
}

class DownloadUrlsDto {
  final String? macos;
  final String? windows;
  final String? linux;
  final String? android;
  final String? ios;

  const DownloadUrlsDto({
    this.macos,
    this.windows,
    this.linux,
    this.android,
    this.ios,
  });

  @override
  int get hashCode =>
      macos.hashCode ^
      windows.hashCode ^
      linux.hashCode ^
      android.hashCode ^
      ios.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadUrlsDto &&
          runtimeType == other.runtimeType &&
          macos == other.macos &&
          windows == other.windows &&
          linux == other.linux &&
          android == other.android &&
          ios == other.ios;
}

enum EffectiveColorSchemeDto { light, dark }

enum EnglishModeDto { ascii, schema }

class FileItemDto {
  final String name;
  final bool isDir;

  const FileItemDto({required this.name, required this.isDir});

  @override
  int get hashCode => name.hashCode ^ isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileItemDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDir == other.isDir;
}

class ImeUiSettingsDto {
  final UiColorSchemeDto colorScheme;
  final EffectiveColorSchemeDto effectiveColorScheme;
  final PanelOrientationDto orientation;
  final bool embeddedComposition;
  final String accentColor;
  final double fontSize;
  final String? themePath;
  final bool themeExists;
  final String? reloadStampPath;
  final String? reloadStampSignature;
  final String message;

  const ImeUiSettingsDto({
    required this.colorScheme,
    required this.effectiveColorScheme,
    required this.orientation,
    required this.embeddedComposition,
    required this.accentColor,
    required this.fontSize,
    this.themePath,
    required this.themeExists,
    this.reloadStampPath,
    this.reloadStampSignature,
    required this.message,
  });

  @override
  int get hashCode =>
      colorScheme.hashCode ^
      effectiveColorScheme.hashCode ^
      orientation.hashCode ^
      embeddedComposition.hashCode ^
      accentColor.hashCode ^
      fontSize.hashCode ^
      themePath.hashCode ^
      themeExists.hashCode ^
      reloadStampPath.hashCode ^
      reloadStampSignature.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImeUiSettingsDto &&
          runtimeType == other.runtimeType &&
          colorScheme == other.colorScheme &&
          effectiveColorScheme == other.effectiveColorScheme &&
          orientation == other.orientation &&
          embeddedComposition == other.embeddedComposition &&
          accentColor == other.accentColor &&
          fontSize == other.fontSize &&
          themePath == other.themePath &&
          themeExists == other.themeExists &&
          reloadStampPath == other.reloadStampPath &&
          reloadStampSignature == other.reloadStampSignature &&
          message == other.message;
}

class InstallProgressDto {
  final String stage;
  final int percent;
  final String message;

  const InstallProgressDto({
    required this.stage,
    required this.percent,
    required this.message,
  });

  @override
  int get hashCode => stage.hashCode ^ percent.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstallProgressDto &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          percent == other.percent &&
          message == other.message;
}

class InstallResultDto {
  final List<String> mergedSchemas;
  final List<String> logs;
  final List<VerifyEntryDto> verify;

  const InstallResultDto({
    required this.mergedSchemas,
    required this.logs,
    required this.verify,
  });

  @override
  int get hashCode => mergedSchemas.hashCode ^ logs.hashCode ^ verify.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstallResultDto &&
          runtimeType == other.runtimeType &&
          mergedSchemas == other.mergedSchemas &&
          logs == other.logs &&
          verify == other.verify;
}

class LocalSchemaDto {
  final bool installed;
  final bool deployed;
  final String? version;
  final List<String> schemas;

  const LocalSchemaDto({
    required this.installed,
    required this.deployed,
    this.version,
    required this.schemas,
  });

  @override
  int get hashCode =>
      installed.hashCode ^
      deployed.hashCode ^
      version.hashCode ^
      schemas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalSchemaDto &&
          runtimeType == other.runtimeType &&
          installed == other.installed &&
          deployed == other.deployed &&
          version == other.version &&
          schemas == other.schemas;
}

class LocalSchemasDto {
  final bool hasDefaultCustom;
  final List<String> schemas;

  const LocalSchemasDto({
    required this.hasDefaultCustom,
    required this.schemas,
  });

  @override
  int get hashCode => hasDefaultCustom.hashCode ^ schemas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalSchemasDto &&
          runtimeType == other.runtimeType &&
          hasDefaultCustom == other.hasDefaultCustom &&
          schemas == other.schemas;
}

class MacosImeStatusDto {
  final bool installed;
  final String? appPath;
  final String? userDataDir;
  final String? sharedDataDir;
  final String sharedDataSource;
  final String? reloadStampPath;
  final String? reloadStampSignature;
  final String? logDir;
  final String message;

  const MacosImeStatusDto({
    required this.installed,
    this.appPath,
    this.userDataDir,
    this.sharedDataDir,
    required this.sharedDataSource,
    this.reloadStampPath,
    this.reloadStampSignature,
    this.logDir,
    required this.message,
  });

  @override
  int get hashCode =>
      installed.hashCode ^
      appPath.hashCode ^
      userDataDir.hashCode ^
      sharedDataDir.hashCode ^
      sharedDataSource.hashCode ^
      reloadStampPath.hashCode ^
      reloadStampSignature.hashCode ^
      logDir.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MacosImeStatusDto &&
          runtimeType == other.runtimeType &&
          installed == other.installed &&
          appPath == other.appPath &&
          userDataDir == other.userDataDir &&
          sharedDataDir == other.sharedDataDir &&
          sharedDataSource == other.sharedDataSource &&
          reloadStampPath == other.reloadStampPath &&
          reloadStampSignature == other.reloadStampSignature &&
          logDir == other.logDir &&
          message == other.message;
}

class OnboardingDto {
  final bool completed;

  const OnboardingDto({required this.completed});

  @override
  int get hashCode => completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnboardingDto &&
          runtimeType == other.runtimeType &&
          completed == other.completed;
}

enum PanelOrientationDto { horizontal, vertical }

class PlatformReleaseDto {
  final String version;
  final DownloadUrlsDto downloadUrls;

  const PlatformReleaseDto({required this.version, required this.downloadUrls});

  @override
  int get hashCode => version.hashCode ^ downloadUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformReleaseDto &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          downloadUrls == other.downloadUrls;
}

class ReleaseInfoDto {
  final String version;
  final String name;
  final String publishedAt;
  final String body;
  final PlatformReleaseDto? github;
  final PlatformReleaseDto? gitee;

  const ReleaseInfoDto({
    required this.version,
    required this.name,
    required this.publishedAt,
    required this.body,
    this.github,
    this.gitee,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      name.hashCode ^
      publishedAt.hashCode ^
      body.hashCode ^
      github.hashCode ^
      gitee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReleaseInfoDto &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          name == other.name &&
          publishedAt == other.publishedAt &&
          body == other.body &&
          github == other.github &&
          gitee == other.gitee;
}

class RuntimeLogFileInfoDto {
  final String name;
  final BigInt size;

  const RuntimeLogFileInfoDto({required this.name, required this.size});

  @override
  int get hashCode => name.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeLogFileInfoDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size;
}

enum RuntimeLogLevelDto { info, verbose }

class RuntimeLogSettingsDto {
  final bool enabled;
  final RuntimeLogLevelDto level;
  final String logDir;
  final List<RuntimeLogFileInfoDto> files;
  final int fileCount;
  final BigInt totalBytes;

  const RuntimeLogSettingsDto({
    required this.enabled,
    required this.level,
    required this.logDir,
    required this.files,
    required this.fileCount,
    required this.totalBytes,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      level.hashCode ^
      logDir.hashCode ^
      files.hashCode ^
      fileCount.hashCode ^
      totalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeLogSettingsDto &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          level == other.level &&
          logDir == other.logDir &&
          files == other.files &&
          fileCount == other.fileCount &&
          totalBytes == other.totalBytes;
}

class SchemeReleaseDto {
  final String scheme;
  final String? sourceType;
  final String label;
  final String version;
  final String name;
  final String? publishedAt;
  final String downloadUrl;
  final String assetName;

  const SchemeReleaseDto({
    required this.scheme,
    this.sourceType,
    required this.label,
    required this.version,
    required this.name,
    this.publishedAt,
    required this.downloadUrl,
    required this.assetName,
  });

  @override
  int get hashCode =>
      scheme.hashCode ^
      sourceType.hashCode ^
      label.hashCode ^
      version.hashCode ^
      name.hashCode ^
      publishedAt.hashCode ^
      downloadUrl.hashCode ^
      assetName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SchemeReleaseDto &&
          runtimeType == other.runtimeType &&
          scheme == other.scheme &&
          sourceType == other.sourceType &&
          label == other.label &&
          version == other.version &&
          name == other.name &&
          publishedAt == other.publishedAt &&
          downloadUrl == other.downloadUrl &&
          assetName == other.assetName;
}

enum UiColorSchemeDto { auto, light, dark }

class VerifyEntryDto {
  final String path;
  final bool ok;
  final String note;

  const VerifyEntryDto({
    required this.path,
    required this.ok,
    required this.note,
  });

  @override
  int get hashCode => path.hashCode ^ ok.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifyEntryDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          ok == other.ok &&
          note == other.note;
}

class WanxiangStatusDto {
  final bool installed;
  final bool deployed;
  final String version;

  const WanxiangStatusDto({
    required this.installed,
    required this.deployed,
    required this.version,
  });

  @override
  int get hashCode => installed.hashCode ^ deployed.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WanxiangStatusDto &&
          runtimeType == other.runtimeType &&
          installed == other.installed &&
          deployed == other.deployed &&
          version == other.version;
}

class WindowsImeStatusDto {
  final bool supported;
  final bool packaged;
  final bool registered;
  final bool registeredDll;
  final bool profileEnabled;
  final bool registrationBusy;
  final String registrationState;
  final String? registrationError;
  final String? runtimeDir;
  final String? dllPath;
  final String? registeredPath;
  final String profileStatus;
  final String? userDataDir;
  final String? sharedDataDir;
  final String sharedDataSource;
  final String? reloadStampPath;
  final String? reloadStampSignature;
  final String message;

  const WindowsImeStatusDto({
    required this.supported,
    required this.packaged,
    required this.registered,
    required this.registeredDll,
    required this.profileEnabled,
    required this.registrationBusy,
    required this.registrationState,
    this.registrationError,
    this.runtimeDir,
    this.dllPath,
    this.registeredPath,
    required this.profileStatus,
    this.userDataDir,
    this.sharedDataDir,
    required this.sharedDataSource,
    this.reloadStampPath,
    this.reloadStampSignature,
    required this.message,
  });

  @override
  int get hashCode =>
      supported.hashCode ^
      packaged.hashCode ^
      registered.hashCode ^
      registeredDll.hashCode ^
      profileEnabled.hashCode ^
      registrationBusy.hashCode ^
      registrationState.hashCode ^
      registrationError.hashCode ^
      runtimeDir.hashCode ^
      dllPath.hashCode ^
      registeredPath.hashCode ^
      profileStatus.hashCode ^
      userDataDir.hashCode ^
      sharedDataDir.hashCode ^
      sharedDataSource.hashCode ^
      reloadStampPath.hashCode ^
      reloadStampSignature.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowsImeStatusDto &&
          runtimeType == other.runtimeType &&
          supported == other.supported &&
          packaged == other.packaged &&
          registered == other.registered &&
          registeredDll == other.registeredDll &&
          profileEnabled == other.profileEnabled &&
          registrationBusy == other.registrationBusy &&
          registrationState == other.registrationState &&
          registrationError == other.registrationError &&
          runtimeDir == other.runtimeDir &&
          dllPath == other.dllPath &&
          registeredPath == other.registeredPath &&
          profileStatus == other.profileStatus &&
          userDataDir == other.userDataDir &&
          sharedDataDir == other.sharedDataDir &&
          sharedDataSource == other.sharedDataSource &&
          reloadStampPath == other.reloadStampPath &&
          reloadStampSignature == other.reloadStampSignature &&
          message == other.message;
}
