// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `eq`, `eq`, `fmt`, `fmt`

class BridgeConfig {
  final String dataDir;
  final String cacheDir;
  final String resourceDir;
  final String appVersion;
  final BridgePlatform platform;

  /// An absolute path. When set, all bridge hosts use this root exclusively.
  final String? userRootOverride;

  const BridgeConfig({
    required this.dataDir,
    required this.cacheDir,
    required this.resourceDir,
    required this.appVersion,
    required this.platform,
    this.userRootOverride,
  });

  @override
  int get hashCode =>
      dataDir.hashCode ^
      cacheDir.hashCode ^
      resourceDir.hashCode ^
      appVersion.hashCode ^
      platform.hashCode ^
      userRootOverride.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeConfig &&
          runtimeType == other.runtimeType &&
          dataDir == other.dataDir &&
          cacheDir == other.cacheDir &&
          resourceDir == other.resourceDir &&
          appVersion == other.appVersion &&
          platform == other.platform &&
          userRootOverride == other.userRootOverride;
}

/// Exactly one payload is present for progress/status events; action/ready have none.
/// Plain structs avoid requiring any Dart code-generation packages.
class BridgeEvent {
  final BridgeEventKind kind;
  final InstallProgressDto? installProgress;
  final String? deployProgress;
  final WindowsImeStatusDto? windowsImeStatus;

  const BridgeEvent({
    required this.kind,
    this.installProgress,
    this.deployProgress,
    this.windowsImeStatus,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      installProgress.hashCode ^
      deployProgress.hashCode ^
      windowsImeStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          installProgress == other.installProgress &&
          deployProgress == other.deployProgress &&
          windowsImeStatus == other.windowsImeStatus;
}

enum BridgeEventKind {
  /// Subscription handshake; subsequent events come from Core's EventSink.
  ready,
  installProgress,
  deployProgress,
  windowsImeStatus,
  windowsImeAction,
}

class BridgeInfo {
  final BridgePlatform platform;
  final String appVersion;
  final String userRoot;

  const BridgeInfo({
    required this.platform,
    required this.appVersion,
    required this.userRoot,
  });

  @override
  int get hashCode =>
      platform.hashCode ^ appVersion.hashCode ^ userRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeInfo &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          appVersion == other.appVersion &&
          userRoot == other.userRoot;
}

enum BridgePlatform { windows, macOs, linux, android, ios }

class InstallProgressDto {
  final String stage;
  final int percent;
  final String message;

  const InstallProgressDto({
    required this.stage,
    required this.percent,
    required this.message,
  });

  @override
  int get hashCode => stage.hashCode ^ percent.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstallProgressDto &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          percent == other.percent &&
          message == other.message;
}

class InstallResultDto {
  final List<String> mergedSchemas;
  final List<String> logs;
  final List<VerifyEntryDto> verify;

  const InstallResultDto({
    required this.mergedSchemas,
    required this.logs,
    required this.verify,
  });

  @override
  int get hashCode => mergedSchemas.hashCode ^ logs.hashCode ^ verify.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstallResultDto &&
          runtimeType == other.runtimeType &&
          mergedSchemas == other.mergedSchemas &&
          logs == other.logs &&
          verify == other.verify;
}

class LocalSchemaDto {
  final bool installed;
  final bool deployed;
  final String? version;
  final List<String> schemas;

  const LocalSchemaDto({
    required this.installed,
    required this.deployed,
    this.version,
    required this.schemas,
  });

  @override
  int get hashCode =>
      installed.hashCode ^
      deployed.hashCode ^
      version.hashCode ^
      schemas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalSchemaDto &&
          runtimeType == other.runtimeType &&
          installed == other.installed &&
          deployed == other.deployed &&
          version == other.version &&
          schemas == other.schemas;
}

class OnboardingDto {
  final bool completed;

  const OnboardingDto({required this.completed});

  @override
  int get hashCode => completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnboardingDto &&
          runtimeType == other.runtimeType &&
          completed == other.completed;
}

class SchemeReleaseDto {
  final String scheme;
  final String? sourceType;
  final String label;
  final String version;
  final String name;
  final String? publishedAt;
  final String downloadUrl;
  final String assetName;

  const SchemeReleaseDto({
    required this.scheme,
    this.sourceType,
    required this.label,
    required this.version,
    required this.name,
    this.publishedAt,
    required this.downloadUrl,
    required this.assetName,
  });

  @override
  int get hashCode =>
      scheme.hashCode ^
      sourceType.hashCode ^
      label.hashCode ^
      version.hashCode ^
      name.hashCode ^
      publishedAt.hashCode ^
      downloadUrl.hashCode ^
      assetName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SchemeReleaseDto &&
          runtimeType == other.runtimeType &&
          scheme == other.scheme &&
          sourceType == other.sourceType &&
          label == other.label &&
          version == other.version &&
          name == other.name &&
          publishedAt == other.publishedAt &&
          downloadUrl == other.downloadUrl &&
          assetName == other.assetName;
}

class VerifyEntryDto {
  final String path;
  final bool ok;
  final String note;

  const VerifyEntryDto({
    required this.path,
    required this.ok,
    required this.note,
  });

  @override
  int get hashCode => path.hashCode ^ ok.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifyEntryDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          ok == other.ok &&
          note == other.note;
}

class WindowsImeStatusDto {
  final bool supported;
  final bool packaged;
  final bool registered;
  final bool registeredDll;
  final bool profileEnabled;
  final bool registrationBusy;
  final String registrationState;
  final String? registrationError;
  final String? runtimeDir;
  final String? dllPath;
  final String? registeredPath;
  final String profileStatus;
  final String? userDataDir;
  final String? sharedDataDir;
  final String sharedDataSource;
  final String? reloadStampPath;
  final String? reloadStampSignature;
  final String message;

  const WindowsImeStatusDto({
    required this.supported,
    required this.packaged,
    required this.registered,
    required this.registeredDll,
    required this.profileEnabled,
    required this.registrationBusy,
    required this.registrationState,
    this.registrationError,
    this.runtimeDir,
    this.dllPath,
    this.registeredPath,
    required this.profileStatus,
    this.userDataDir,
    this.sharedDataDir,
    required this.sharedDataSource,
    this.reloadStampPath,
    this.reloadStampSignature,
    required this.message,
  });

  @override
  int get hashCode =>
      supported.hashCode ^
      packaged.hashCode ^
      registered.hashCode ^
      registeredDll.hashCode ^
      profileEnabled.hashCode ^
      registrationBusy.hashCode ^
      registrationState.hashCode ^
      registrationError.hashCode ^
      runtimeDir.hashCode ^
      dllPath.hashCode ^
      registeredPath.hashCode ^
      profileStatus.hashCode ^
      userDataDir.hashCode ^
      sharedDataDir.hashCode ^
      sharedDataSource.hashCode ^
      reloadStampPath.hashCode ^
      reloadStampSignature.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowsImeStatusDto &&
          runtimeType == other.runtimeType &&
          supported == other.supported &&
          packaged == other.packaged &&
          registered == other.registered &&
          registeredDll == other.registeredDll &&
          profileEnabled == other.profileEnabled &&
          registrationBusy == other.registrationBusy &&
          registrationState == other.registrationState &&
          registrationError == other.registrationError &&
          runtimeDir == other.runtimeDir &&
          dllPath == other.dllPath &&
          registeredPath == other.registeredPath &&
          profileStatus == other.profileStatus &&
          userDataDir == other.userDataDir &&
          sharedDataDir == other.sharedDataDir &&
          sharedDataSource == other.sharedDataSource &&
          reloadStampPath == other.reloadStampPath &&
          reloadStampSignature == other.reloadStampSignature &&
          message == other.message;
}
