[package]
name = "keytao-app-core"
version.workspace = true
edition = "2024"

[dependencies]
serde.workspace = true
serde_json = "1"
tempfile = "3"
serde_yaml = "0.9"
reqwest = { version = "0.12", features = ["json", "stream", "rustls-tls"], default-features = false }
futures-util = "0.3"
sha2 = "0.10"
zip = { version = "2", default-features = false, features = ["deflate", "time"] }
tokio = { version = "1", features = ["full"] }
keytao-core = { path = "../keytao-core" }
tracing = "0.1"
