// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'api/types.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<BridgeEvent> dco_decode_StreamSink_bridge_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddonSchemaStatusDto dco_decode_addon_schema_status_dto(dynamic raw);

  @protected
  AndroidImeInputSettingsDto dco_decode_android_ime_input_settings_dto(
    dynamic raw,
  );

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AndroidImeInputSettingsDto
  dco_decode_box_autoadd_android_ime_input_settings_dto(dynamic raw);

  @protected
  BridgeConfig dco_decode_box_autoadd_bridge_config(dynamic raw);

  @protected
  InstallProgressDto dco_decode_box_autoadd_install_progress_dto(dynamic raw);

  @protected
  PlatformReleaseDto dco_decode_box_autoadd_platform_release_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  WindowsImeStatusDto dco_decode_box_autoadd_windows_ime_status_dto(
    dynamic raw,
  );

  @protected
  BridgeConfig dco_decode_bridge_config(dynamic raw);

  @protected
  BridgeEvent dco_decode_bridge_event(dynamic raw);

  @protected
  BridgeEventKind dco_decode_bridge_event_kind(dynamic raw);

  @protected
  BridgeInfo dco_decode_bridge_info(dynamic raw);

  @protected
  BridgePlatform dco_decode_bridge_platform(dynamic raw);

  @protected
  ComponentVersionsDto dco_decode_component_versions_dto(dynamic raw);

  @protected
  DebugLogFileDto dco_decode_debug_log_file_dto(dynamic raw);

  @protected
  DeployResultDto dco_decode_deploy_result_dto(dynamic raw);

  @protected
  DownloadUrlsDto dco_decode_download_urls_dto(dynamic raw);

  @protected
  EffectiveColorSchemeDto dco_decode_effective_color_scheme_dto(dynamic raw);

  @protected
  EnglishModeDto dco_decode_english_mode_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImeUiSettingsDto dco_decode_ime_ui_settings_dto(dynamic raw);

  @protected
  InstallProgressDto dco_decode_install_progress_dto(dynamic raw);

  @protected
  InstallResultDto dco_decode_install_result_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RuntimeLogFileInfoDto> dco_decode_list_runtime_log_file_info_dto(
    dynamic raw,
  );

  @protected
  List<VerifyEntryDto> dco_decode_list_verify_entry_dto(dynamic raw);

  @protected
  LocalSchemaDto dco_decode_local_schema_dto(dynamic raw);

  @protected
  MacosImeStatusDto dco_decode_macos_ime_status_dto(dynamic raw);

  @protected
  OnboardingDto dco_decode_onboarding_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  InstallProgressDto? dco_decode_opt_box_autoadd_install_progress_dto(
    dynamic raw,
  );

  @protected
  PlatformReleaseDto? dco_decode_opt_box_autoadd_platform_release_dto(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  WindowsImeStatusDto? dco_decode_opt_box_autoadd_windows_ime_status_dto(
    dynamic raw,
  );

  @protected
  PanelOrientationDto dco_decode_panel_orientation_dto(dynamic raw);

  @protected
  PlatformReleaseDto dco_decode_platform_release_dto(dynamic raw);

  @protected
  ReleaseInfoDto dco_decode_release_info_dto(dynamic raw);

  @protected
  RuntimeLogFileInfoDto dco_decode_runtime_log_file_info_dto(dynamic raw);

  @protected
  RuntimeLogLevelDto dco_decode_runtime_log_level_dto(dynamic raw);

  @protected
  RuntimeLogSettingsDto dco_decode_runtime_log_settings_dto(dynamic raw);

  @protected
  SchemeReleaseDto dco_decode_scheme_release_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiColorSchemeDto dco_decode_ui_color_scheme_dto(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VerifyEntryDto dco_decode_verify_entry_dto(dynamic raw);

  @protected
  WindowsImeStatusDto dco_decode_windows_ime_status_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<BridgeEvent> sse_decode_StreamSink_bridge_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddonSchemaStatusDto sse_decode_addon_schema_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  AndroidImeInputSettingsDto sse_decode_android_ime_input_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AndroidImeInputSettingsDto
  sse_decode_box_autoadd_android_ime_input_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeConfig sse_decode_box_autoadd_bridge_config(
    SseDeserializer deserializer,
  );

  @protected
  InstallProgressDto sse_decode_box_autoadd_install_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformReleaseDto sse_decode_box_autoadd_platform_release_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WindowsImeStatusDto sse_decode_box_autoadd_windows_ime_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeConfig sse_decode_bridge_config(SseDeserializer deserializer);

  @protected
  BridgeEvent sse_decode_bridge_event(SseDeserializer deserializer);

  @protected
  BridgeEventKind sse_decode_bridge_event_kind(SseDeserializer deserializer);

  @protected
  BridgeInfo sse_decode_bridge_info(SseDeserializer deserializer);

  @protected
  BridgePlatform sse_decode_bridge_platform(SseDeserializer deserializer);

  @protected
  ComponentVersionsDto sse_decode_component_versions_dto(
    SseDeserializer deserializer,
  );

  @protected
  DebugLogFileDto sse_decode_debug_log_file_dto(SseDeserializer deserializer);

  @protected
  DeployResultDto sse_decode_deploy_result_dto(SseDeserializer deserializer);

  @protected
  DownloadUrlsDto sse_decode_download_urls_dto(SseDeserializer deserializer);

  @protected
  EffectiveColorSchemeDto sse_decode_effective_color_scheme_dto(
    SseDeserializer deserializer,
  );

  @protected
  EnglishModeDto sse_decode_english_mode_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImeUiSettingsDto sse_decode_ime_ui_settings_dto(SseDeserializer deserializer);

  @protected
  InstallProgressDto sse_decode_install_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  InstallResultDto sse_decode_install_result_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RuntimeLogFileInfoDto> sse_decode_list_runtime_log_file_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<VerifyEntryDto> sse_decode_list_verify_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  LocalSchemaDto sse_decode_local_schema_dto(SseDeserializer deserializer);

  @protected
  MacosImeStatusDto sse_decode_macos_ime_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  OnboardingDto sse_decode_onboarding_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  InstallProgressDto? sse_decode_opt_box_autoadd_install_progress_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformReleaseDto? sse_decode_opt_box_autoadd_platform_release_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WindowsImeStatusDto? sse_decode_opt_box_autoadd_windows_ime_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  PanelOrientationDto sse_decode_panel_orientation_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformReleaseDto sse_decode_platform_release_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReleaseInfoDto sse_decode_release_info_dto(SseDeserializer deserializer);

  @protected
  RuntimeLogFileInfoDto sse_decode_runtime_log_file_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  RuntimeLogLevelDto sse_decode_runtime_log_level_dto(
    SseDeserializer deserializer,
  );

  @protected
  RuntimeLogSettingsDto sse_decode_runtime_log_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  SchemeReleaseDto sse_decode_scheme_release_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiColorSchemeDto sse_decode_ui_color_scheme_dto(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VerifyEntryDto sse_decode_verify_entry_dto(SseDeserializer deserializer);

  @protected
  WindowsImeStatusDto sse_decode_windows_ime_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_event_Sse(
    RustStreamSink<BridgeEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_addon_schema_status_dto(
    AddonSchemaStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_android_ime_input_settings_dto(
    AndroidImeInputSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_android_ime_input_settings_dto(
    AndroidImeInputSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_config(
    BridgeConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_install_progress_dto(
    InstallProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_platform_release_dto(
    PlatformReleaseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_windows_ime_status_dto(
    WindowsImeStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_config(BridgeConfig self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_event(BridgeEvent self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_event_kind(
    BridgeEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_info(BridgeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_platform(
    BridgePlatform self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_component_versions_dto(
    ComponentVersionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_debug_log_file_dto(
    DebugLogFileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_deploy_result_dto(
    DeployResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_urls_dto(
    DownloadUrlsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_effective_color_scheme_dto(
    EffectiveColorSchemeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_english_mode_dto(
    EnglishModeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_ime_ui_settings_dto(
    ImeUiSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_install_progress_dto(
    InstallProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_install_result_dto(
    InstallResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_runtime_log_file_info_dto(
    List<RuntimeLogFileInfoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_verify_entry_dto(
    List<VerifyEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_schema_dto(
    LocalSchemaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_macos_ime_status_dto(
    MacosImeStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_onboarding_dto(OnboardingDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_install_progress_dto(
    InstallProgressDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_platform_release_dto(
    PlatformReleaseDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_windows_ime_status_dto(
    WindowsImeStatusDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_panel_orientation_dto(
    PanelOrientationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_platform_release_dto(
    PlatformReleaseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_release_info_dto(
    ReleaseInfoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_runtime_log_file_info_dto(
    RuntimeLogFileInfoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_runtime_log_level_dto(
    RuntimeLogLevelDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_runtime_log_settings_dto(
    RuntimeLogSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scheme_release_dto(
    SchemeReleaseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_color_scheme_dto(
    UiColorSchemeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_verify_entry_dto(
    VerifyEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_windows_ime_status_dto(
    WindowsImeStatusDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
